# Generated by Django 5.1.5 on 2026-09-17 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(help_text='Prix avec coffret')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='NovaSneak', max_length=100)),
                ('whatsapp_number', models.CharField(help_text="Format international sans '+', ex: 2250700000000", max_length=20)),
                ('box_discount', models.PositiveIntegerField(default=1000, help_text='Remise appliquee si le client ne prend pas le coffret')),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('size_min', models.PositiveIntegerField(default=37)),
                ('size_max', models.PositiveIntegerField(default=47)),
            ],
            options={
                'verbose_name': 'Parametres de la boutique',
                'verbose_name_plural': 'Parametres de la boutique',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
