# Generated by Django 5.1.5 on 2026-09-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'produit', 'verbose_name_plural': 'produits'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'image produit', 'verbose_name_plural': 'images produit'},
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Prix avec coffret', verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='box_discount',
            field=models.PositiveIntegerField(default=1000, help_text='Remise appliquee si le client ne prend pas le coffret', verbose_name='Remise sans coffret'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='currency',
            field=models.CharField(default='FCFA', max_length=10, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='size_max',
            field=models.PositiveIntegerField(default=47, verbose_name='Pointure maximum'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='size_min',
            field=models.PositiveIntegerField(default=37, verbose_name='Pointure minimum'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='store_name',
            field=models.CharField(default='NovaSneak', max_length=100, verbose_name='Nom de la boutique'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='whatsapp_number',
            field=models.CharField(help_text="Format international sans '+', ex: 2250700000000", max_length=20, verbose_name='Numero WhatsApp'),
        ),
    ]
