# Generated by Django 5.1.5 on 2026-09-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de la commande')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('currency', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Prix unitaire')),
                ('size', models.PositiveIntegerField(verbose_name='Pointure')),
                ('with_box', models.BooleanField(default=True, verbose_name='Avec coffret')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantite')),
                ('color_note', models.CharField(blank=True, max_length=200, verbose_name='Couleur souhaitee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.order', verbose_name='Commande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'article commande',
                'verbose_name_plural': 'articles commande',
            },
        ),
    ]
